
    CREATE TABLE IF NOT EXISTS basic_info (
      `id` int(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    company Text(200), 
    mobile Text(200),
`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
